name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Version
        id: gitversion
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build

      - name: Sources
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: sourcesJar

      - name: Javadoc
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: javadocJar --no-daemon

      - name: Publish package
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: sign publishToSonatype closeAndReleaseSonatypeStagingRepository --info
        env:
          MAVEN_VERSION: ${{ steps.gitversion.outputs.version }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_ID: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_ID }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/main' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'refs/tags/${{steps.gitversion.outputs.version}}'
          release_name: ${{ steps.gitversion.outputs.version }}
          draft: false
          prerelease: false