name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Version
        id: gitversion
        uses: codacy/git-version@2.8.6
        with:
          release-branch: main
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Build
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew build

      - name: Sources
        run: ./gradlew sourcesJar

      - name: Javadoc
        run: ./gradlew javadocJar

      - name: Publish package
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew sign publishToSonatype closeAndReleaseSonatypeStagingRepository --info
        env:
          MAVEN_VERSION: ${{ steps.gitversion.outputs.version }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_ID: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_ID }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/main' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'refs/tags/${{steps.gitversion.outputs.version}}'
          name: ${{ steps.gitversion.outputs.version }}
          draft: false
          prerelease: false